baseurl = "http://www.markusbodner.com"
title = "Markus Bodner"
copyright = "Copyright 2015 by Markus Bodner"

footnotereturnlinkcontents = "↩"

[author]
	name = "Markus Bodner"
	email = "hello@markusbodner.com"
	twitter = "tuacker"

[permalinks]
	post = ":year/:month/:day/:title/"

[taxonomies]
	tag = "tags"
