baseurl = "http://www.markusbodner.com"
languageCode = "en-us" 
title = "Markus Bodner"

footnotereturnlinkcontents = "↩"

[author]
	name = "Markus Bodner"

[permalinks]
	post = ":year/:month/:day/:title/"

[taxonomies]
	tag = "tags"
