baseURL = "https://www.markusbodner.com/"
languageCode = "en-us"
title = "Markus Bodner"

footnoteReturnLinkContents = "↩"
enableGitInfo = true
enableRobotsTXT  = true

theme = "personal-blue"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

[permalinks]
  post = ":year/:month/:day/:title/"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Blog"
  weight = 1
  identifier = "post"
  url = "/"

[[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Newsletter"
  weight = 3
  identifier = "newsletter"
  url = "/newsletter"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100
[[related.indices]]
  name = "date"
  weight = 10

[blackfriday]
  plainIDAnchors = true


# Custom params
[params]
  googleSiteVerification = "wNJ6f3EUjLyWtEIj8NWn0Y9QiovwvrpcXGNc2_CFpkM"
  description = "Website of Markus Bodner. Learn more about me here and read my blog."
  images = ["images/markus_bodner.jpg"]

[params.author]
  name = "Markus Bodner"
  email = "me@markusbodner.com"
  twitter = "tuacker"
