baseURL = "https://www.markusbodner.com/"
languageCode = "en-us"
title = "Markus Bodner"

footnoteReturnLinkContents = "↩"
enableGitInfo = true
enableRobotsTXT  = true

theme = "personal-blue"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

canonifyURLs = true

disableKinds = ["section"]

[outputs]
  home     = ["HTML", "RSS"]
  section  = ["HTML"]

[permalinks]
  post = ":year/:month/:day/:slug/"
  til = "til/:year/:month/:day/:slug/"
  quote = "quote/:year/:month/:day/:slug/"
  page = ":filename/"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "post"
  url = "/"

[[menu.main]]
  name = "Gallery"
  weight = 4
  identifier = "gallery"
  url = "/gallery/"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100
[[related.indices]]
  name = "date"
  weight = 10

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    enableDNT = true
    simple = true
  [privacy.vimeo]
    simple = false
  [privacy.youtube]
    privacyEnhanced = true


# Custom params
[params]
  description = "Website of Markus Bodner. Learn more about me here and read my blog."
  images = ["images/markus_bodner.jpg"]
  mainSections = ["post", "til", "quote"]

[params.author]
  name = "Markus Bodner"
  email = "me@markusbodner.com"
  twitter = "tuacker"
