baseURL = "https://www.markusbodner.com/"
languageCode = "en-us"
title = "Markus Bodner"

footnoteReturnLinkContents = "↩"
enableGitInfo = true
enableRobotsTXT  = true

[permalinks]
  post = ":year/:month/:day/:title/"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "keywords"
  weight = 100
[[related.indices]]
  name = "tags"
  weight = 50
[[related.indices]]
  name = "date"
  weight = 10

[blackfriday]
  plainIDAnchors = true
