[build]
  publish = "public"
  command = "hugo --gc --minify"
  HUGO_VERSION = "0.52"

[context.production.environment]
  HUGO_VERSION = "0.52"


[context.deploy-preview]
  command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.52"

[context.branch-deploy]
  command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.52"
