# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Personal Blue"
license = "MIT"
licenselink = "https://gitlab.com/tuacker/markusbodner.com/themes/personal-blue/blob/master/LICENSE"
description = "A blue-ish theme for my personal website"
homepage = "https://www.markusbodner.com.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Markus Bodner"
  homepage = "https://www.markusbodner.com.com/"
